export const DataGridDummyRows = [
  {
    id: 1,
    name: "Freddo Espresso",
    location: "Framboise",
    category: "Coffee",
    price: 2.3,
    time: 1660467000000,
  },
  {
    id: 2,
    name: "Freddo Espresso",
    location: "JOJO Kipseli",
    category: "Coffee",
    price: 3,
    time: 1665167000000,
  },
  {
    id: 3,
    name: "Vape e-liquid",
    location: "Vape Cargo",
    category: "Vape",
    price: 23,
    time: 1660467000000,
  },
  {
    id: 4,
    name: "Netum Receipt Printer",
    location: "Alexopoulos Electronics",
    category: "Business",
    price: 38,
    time: 1630167000000,
  },
  {
    id: 5,
    name: "Cheddar/bacon loukoumades",
    location: "LUKUMADES",
    category: "Fast food",
    price: 4.9,
    time: 1660167000000,
  },
  {
    id: 6,
    name: "3kg tomatoes",
    location: "MyMarket",
    category: "Groceries",
    price: 4.3,
    time: 1680167000000,
  },
  {
    id: 7,
    name: "23L gasoline",
    location: "Shell Str. Kallari",
    category: "Fuel",
    price: 46,
    time: 1600167000000,
  },
  {
    id: 8,
    name: "Corona beer",
    location: "Dos Gardenias",
    category: "Drinks",
    price: 6,
    time: 1660167000000,
  },
];

export const DataGridDummyColumns = [
  {
    position: 0,
    key: "id",
    label: "ID",
    sortable: false,
    size: "280px",
    hidden: true,
  },
  {
    position: 1,
    key: "name",
    label: "Item name",
    sortable: false,
    size: "280px",
    hidden: false,
  },
  {
    position: 3,
    key: "location",
    label: "Location",
    sortable: false,
    size: "230px",
    hidden: false,
  },
  {
    position: 2,
    key: "category",
    label: "Category",
    sortable: true,
    size: "150px",
    hidden: false,
  },
  {
    position: 4,
    key: "price",
    label: "Spent",
    sortable: true,
    size: "120px",
    hidden: false,
  },
  {
    position: 5,
    key: "time",
    label: "Date",
    sortable: true,
    size: "230px",
    hidden: false,
  },
];
